import React,{useState} from 'react'
import {FormField, Loader, Card} from '../components/page components/index'

const RenderCards = ({data, title}) => {
    if (data?.length > 0){
        return data.map((post) => <Card key={post._id} {...post}/> )
    }

    return(
        <h2>
            {title}
        </h2>
    )
}

const Home = () => {
    const [loading, setLoading] = useState(false)
    const [allposts, setAllPosts] = useState(null)
  
    const [searchText, setSearchText] = useState('ifdsh')
    return (
    <main className='w-[80%] md:w-[75%] mx-auto my-[2rem]'>
        <article>
        <h1 className='text-5xl md:text-6xl my-3'>Community Showcase</h1>
        <h2 className='text-2xl md:text-3xl text-neutral-400'>
            Browse through creative and stunning images generated by AI
        </h2>
        </article>

        <section className='my-[2rem]'>
            <FormField/>
        </section>

        <section className='my-[2rem]'>
        {
            loading ? (
                <Loader/>
            ) : (
                <>
                {
                    searchText && 
                    <h1 className='text-neutral-200 text-xl md:text-2xl'>search results for <span className='font-bold'>{searchText}</span></h1>
                }

                <div>
                    {
                        searchText ?
                        (
                            <RenderCards
                            data={[]}
                            title="No search results found"
                            />
                        ) : (
                            <RenderCards
                            data={[]}
                            title="No posts found"
                            />
                        )
                    }
                </div>
                </>
            )
        }
        </section>        
    </main>
  )
}

export default Home